### ISSUE TITLE
图片翻译可以做吗？

### ISSUE THREAD

**Issue by Jengro777** [spywiree/googletranslate#6]
![image](https://github.com/spywiree/googletranslate/assets/35259040/eadfce84-a9f4-4009-b55f-59c729f2c7ac)

**Comment by spywiree** [comment]
No, you can't. This feature will be added in version 2 of this package (if I can find some endpoints).

**Comment by Jengro777** [comment]
> No, you can't. This feature will be added in version 2 of this package (if I can find some endpoints).

I hope you can find a way to translate images
